name: Core
version: 1.0.0-SNAPSHOT
main: net.nighthawkempires.core.CorePlugin
description: Nighthawk Empires' Core Plugin.
author: NoneVale_
api-version: 1.17
libraries:
  - org.mongodb:bson:3.8.2
  - org.mongodb:mongodb-driver:3.8.2
  - org.mongodb:mongodb-driver-core:3.8.2
  - org.apache.commons:commons-lang3:3.9